#!/bin/bash
set -e

echo "[init] create wordpress databases and users"

mariadb -uroot -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS \`${MARIADB_SITE1_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE DATABASE IF NOT EXISTS \`${MARIADB_SITE2_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE DATABASE IF NOT EXISTS \`${MARIADB_SITE3_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

  CREATE USER IF NOT EXISTS '${MARIADB_SITE1_USER}'@'%' IDENTIFIED BY '${MARIADB_SITE1_PASSWORD}';
  CREATE USER IF NOT EXISTS '${MARIADB_SITE2_USER}'@'%' IDENTIFIED BY '${MARIADB_SITE2_PASSWORD}';
  CREATE USER IF NOT EXISTS '${MARIADB_SITE3_USER}'@'%' IDENTIFIED BY '${MARIADB_SITE3_PASSWORD}';

  GRANT ALL PRIVILEGES ON \`${MARIADB_SITE1_DB}\`.* TO '${MARIADB_SITE1_USER}'@'%';
  GRANT ALL PRIVILEGES ON \`${MARIADB_SITE2_DB}\`.* TO '${MARIADB_SITE2_USER}'@'%';
  GRANT ALL PRIVILEGES ON \`${MARIADB_SITE3_DB}\`.* TO '${MARIADB_SITE3_USER}'@'%';

  FLUSH PRIVILEGES;
EOSQL
